export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'
export const LOGOUT_USER = 'LOGOUT_USER'

export const GET_LANGUAGES = 'GET_LANGUAGES'
export const GET_LANGUAGES_SUCCESS = 'GET_LANGUAGES_SUCCESS'
export const GET_LANGUAGES_ERROR = 'GET_LANGUAGES_ERROR'

export const DELETE_LANGUAGE = 'DELETE_LANGUAGE'
export const DELETE_LANGUAGE_SUCCESS = 'DELETE_LANGUAGE_SUCCESS'
export const DELETE_LANGUAGE_ERROR = 'DELETE_LANGUAGE_ERROR'

export const ADD_LANGUAGE = 'ADD_LANGUAGE'
export const ADD_LANGUAGE_SUCCESS = 'ADD_LANGUAGE_SUCCESS'
export const ADD_LANGUAGE_ERROR = 'ADD_LANGUAGE_ERROR'

export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE'
export const UPDATE_LANGUAGE_SUCCESS = 'UPDATE_LANGUAGE_SUCCESS'
export const UPDATE_LANGUAGE_ERROR = 'UPDATE_LANGUAGE_ERROR'

export const LANGUAGES_MODAL_ISOPEN = 'LANGUAGES_MODAL_ISOPEN'

export const GET_SERVICES = 'GET_SERVICES'
export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS'
export const GET_SERVICES_ERROR = 'GET_SERVICES_ERROR'

export const DELETE_SERVICE = 'DELETE_SERVICE'
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS'
export const DELETE_SERVICE_ERROR = 'DELETE_SERVICE_ERROR'

export const ADD_SERVICE = 'ADD_SERVICE'
export const ADD_SERVICE_SUCCESS = 'ADD_SERVICE_SUCCESS'
export const ADD_SERVICE_ERROR = 'ADD_SERVICE_ERROR'

export const UPDATE_SERVICE = 'UPDATE_SERVICE'
export const UPDATE_SERVICE_SUCCESS = 'UPDATE_SERVICE_SUCCESS'
export const UPDATE_SERVICE_ERROR = 'UPDATE_SERVICE_ERROR'

export const SERVICES_MODAL_ISOPEN = 'SERVICES_MODAL_ISOPEN'
export const SET_SERVICES_EDITING_ID = 'SET_SERVICES_EDITING_ID'

export const GET_ORDERS = 'GET_ORDERS'
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS'
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR'

export const GET_ORDER_BY_ID_STARTED = 'GET_ORDER_BY_ID_STARTED'
export const GET_ORDER_BY_ID_SUCCEED = 'GET_ORDER_BY_ID_SUCCEED'
export const GET_ORDER_BY_ID_FAILED = 'GET_ORDER_BY_ID_FAILED'

export const DELETE_ORDER = 'DELETE_ORDER'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_ERROR = 'DELETE_ORDER_ERROR'

export const ADD_ORDER = 'ADD_ORDER'
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS'
export const ADD_ORDER_ERROR = 'ADD_ORDER_ERROR'

export const UPDATE_ORDER = 'UPDATE_ORDER'
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS'
export const UPDATE_ORDER_ERROR = 'UPDATE_ORDER_ERROR'

export const ORDERS_MODAL_ISOPEN = 'ORDERS_MODAL_ISOPEN'
export const ORDER_IS_EDITING = 'ORDER_IS_EDITING'

export const GET_CLIENTS = 'GET_CLIENTS'
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS'
export const GET_CLIENTS_ERROR = 'GET_CLIENTS_ERROR'
export const GET_CLIENT_BY_ID = 'GET_CLIENT_BY_ID'
export const GET_CLIENT_BY_ID_SUCCESS = 'GET_CLIENT_BY_ID_SUCCESS'
export const GET_CLIENT_BY_ID_ERROR = 'GET_CLIENT_BY_ID_ERROR'
export const ADD_CLIENT = 'ADD_CLIENT'
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS'
export const ADD_CLIENT_ERROR = 'ADD_CLIENT_ERROR'
export const DELETE_CLIENT = 'DELETE_CLIENT'
export const DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS'
export const DELETE_CLIENT_ERROR = 'DELETE_CLIENT_ERROR'
export const UPDATE_CLIENT = 'UPDATE_CLIENT'
export const UPDATE_CLIENT_SUCCESS = 'UPDATE_CLIENT_SUCCESS'
export const UPDATE_CLIENT_ERROR = 'UPDATE_CLIENT_ERROR'
export const SET_CLIENT_EDITING_ID = 'SET_CLIENT_EDITING_ID'

export const CLIENTS_MODAL_ISOPEN = 'CLIENTS_MODAL_ISOPEN'

export const SET_LOADING_CELL = 'SET_LOADING_CELL'

export const GET_ERRORS = 'GET_ERRORS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const GET_PROFILE = 'GET_PROFILE'
export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND'
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE'
export const GET_PROFILES = 'GET_PROFILES'
export const ADD_EXPERIENCE = 'ADD_EXPERIENCE'
export const GET_POSTS = 'GET_POSTS'
export const POST_LOADING = 'PROFILE_LOADING'
export const GET_POST = 'GET_POST'
export const ADD_POST = 'ADD_POST'
export const DELETE_POST = 'DELETE_POST'
export const LIKE_POST = 'LIKE_POST'
export const ADD_COMMENT = 'ADD_COMMENT'
export const GET_CURRENT_USER = 'GET_CURRENT_USER'

export enum AUTH_ACTIONS {
  LOGIN = 'LOGIN',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_ERROR = 'LOGIN_ERROR',
}

export enum USER_ACTIONS {
  REGISTER_USER = 'REGISTER_USER',
  REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS',
  REGISTER_USER_ERROR = 'REGISTER_USER_ERROR',
  GET_CURRENT_USER = 'GET_CURRENT_USER',
  GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS',
  GET_CURRENT_USER_ERROR = 'GET_CURRENT_USER_ERROR',
}
